### ISSUE TITLE
How to extend existing Elmish apps

### ISSUE THREAD

**Issue by SCullman** [dbrattli/Fable.Reaction#13]
My current, already existing Elmish project would benefit from an Autocomplete feature. 
 I added the dependency for Reaction, added 
```Program.withMsgStream App.stream "msgs"```
Well, and already here I am lost.
I thought I can just filter / choose the right events and pass it down to the right sub component.
```fsharp
let stream model msgs =
    let asSubCompMsg msg =
        match msg with
        | SubCompMsg msg -> Some msg
        | _ -> None

    match model with
    | Loaded model -> SubComponent.State.stream model.SubComponent (AsyncRx.choose asSubCompMsg msgs)
    | _ -> Stream.none
``` 
...and so on, similar how sub components are initialized/updated in Elmish.

To my first surprise, my app stopped working, as no messages were passed anymore. I just did not expect that the stream acts as a filter. 

At that point of time I just wanted to get the app running again. 
So i changed my stream method to
```let stream model msgs = AsyncRx.toStream "msgs" msgs````
I expected that now all messages will remain unchanged as before. But no, it still did not process msgs anymore.

If I comment ``Program.withMsgStream``, the app works again (beside autocomplete, of course).
I guess I am missing something obvious.

**Comment by dbrattli** [comment]
You also need to return the original `msgs` if you need them for your app. You can use `Stream.batch` for this e.g:

```fs
Stream.batch [
    subMsgs
    msgs
] 
```
See here for full example: https://github.com/rommsen/Fable.Reaction.Playground/blob/master/src/Client/Client.fs

**Comment by SCullman** [comment]
Ok, getting near.

```fsharp
let stream model msgs =
    let asSubCompMsg msg =
        match msg with
        | SubCompMsg msg -> Some msg
        | _ -> None
    
    let subMsgs = 
          msgs
          |> Strean.choose asSubCompMsg msgs
          |> SubComponent.State.stream model.SubComponent 
          |> Stream.map SubCompMsg

    Stream.batch 
        [ subMsgs
          msgs ]
```
This pattern will be repeated again in ``SubComponent.State.stream`` if SubComponent is also a composition of deeper SubComponents.

However, the simplest implementation of SubComponent.State.stream would be 
```fsharp
let stream model msgs = Stream.batch  [msgs] //doing nothing
```

In that case we would double the msgs of the subComponent, won't we?
Shouldn't we partition the msgs?

```fsharp
    Stream.batch 
        [ subMsgs
          msgs |> List.filter (fun msg -> msg |> asSubCompMsg |> Option.isNone)  ]
```

**Comment by dbrattli** [comment]
I guess it depends, so for now it's up to the developer to choose the way things should work. The way I have been thinking about it so far has been that the subcomponent only produces new messages, and do not bounce back the received messages. Then the simplest subcomponent would be: 

```fs
let stream model msgs = Stream.none // doing nothing
```

**Comment by SCullman** [comment]
Well, it happens frequently to me that my main App turns into a sub component, and than suddenly I would expect ``App.stream`` to return only new messages instead of new and old messages. 
I think  ``Stream.none`` instead of ``Stream.batch [ msgs ]`` violates a kind of symmetry.

Anyway, thank you @dbrattli. This will really help me further with my current project.

**Comment by dbrattli** [comment]
Yes, that is a good point. I like the idea of having symmetry and that pages might evolve into componets and sub-components.

**Comment by SCullman** [comment]
Sigh! ``msgs`` is not a ``msg list`` and can't be simply filtered.

```fsharp
let subStream stream fromSubMsg asSubMsg model msgs = 

    let streamedMsgs = 
        msgs
        |> Stream.choose asSubMsg
        |> stream model
        |> Stream.map fromSubMsg

    let otherMsgs =
        msgs 
        |> Stream.choose (fun msg -> match asSubMsg msg with None -> Some msg | _ -> None )

    streamedMsgs, otherMsgs


let stream model msgs =

        let asSubCompMsg msg = match msg with SubCompMsg m -> Some m | _-> None

        let (streamed, others)  = subStream SubComponent.State.stream 
                                                SubCompMsg asSubCompMsg  
                                                model.SubComponent msgs

        // it would be possible to pass now others to a second sub component :-)

        Stream.batch
            [ streamed
              others ] 
```

**Comment by dbrattli** [comment]
Stream is a single case union of a list containing named async observable streams.

I've added `filter` to streams, and also considering adding a `partition` operator. You can try out the function below if that makes things cleaner. 

```fs
    /// Filter stream based on given predicate.
    let filter (predicate: 'msg -> bool) : Stream<'msg, 'name> -> Stream<'msg, 'name> =
        function
        | Stream xss ->
            xss
            |> List.map (fun (xs, name) -> (xs |> AsyncRx.filter predicate, name))
            |> Stream
```

I will try to push out a new release tomorrow.

**Comment by SCullman** [comment]
Nice enhancement. Please add!

What if we add a ``Program.withAdditionalMsgStream (stream: 'model -> Stream<'msg, 'name> -> Stream<'msg, 'name>) (program: Elmish.Program<_,_,_,_>)``?     

Set the initialName always to "msgs".    
And, in the inner ``view`` function, 
```fsharp
let (Stream streams) = 
    Stream [obs, initialName] |> fun msgs -> Stream.batch [ stream model; msgs ]
```

Now the original messages remain unchanged. ``stream`` would only inject new messages.
A subcomponent which doesn't require AsyncRx can now simply return ``Stream.none`` just like you wrote before.

**Comment by dbrattli** [comment]
Sorry for the delay, been busy with other stuff. I'm not that happy with adding another method as it will just add to the confusion on how to use the library. It should also be easy to just compose the `stream` function to do what you describe. Some sub-components will need to receive messages, others only produce messages.

There is a new version 2.5.0 out with new `Stream` functions such as `tap`, `filter` and `chooseNot`:

```fs
    /// Filter stream based on given predicate.
    let filter (predicate: 'msg -> bool) : Stream<'msg, 'name> -> Stream<'msg, 'name> = function
        | Stream xss ->
            xss
            |> List.map (fun (xs, name) -> xs |> AsyncRx.filter predicate, name)
            |> Stream

    /// Applies the given chooser function to each element of the stream and
    /// returns the stream comprised of the results for each element where the
    /// function returns with None value.
    let chooseNot chooser =
        filter (chooser >> Option.isNone)

    /// Tap into stream and print messages to console. The tag is a
    /// string used to give yourself a hint of where the tap is
    /// inserted. Returns the stream unmodified.
    let tap tag : Stream<'msg, 'name> -> Stream<'msg, 'name> = function
        | Stream xss ->
            xss
            |> List.map (fun (xs, name) -> xs |> AsyncRx.tapOnNext (printfn "[Reaction] \"%s\" (%A) - %A" tag   name), name)
            |> Stream
```

This means that you can now either remove the sub-messages from the main msg stream using `chooseNot`, or you can inject just `Stream.none` to the sub-component to avoid filtering output from it e.g.

```fs
    Stream.batch
        [
          msgs |> Stream.chooseNot asInfoMsg
          msgs |> Stream.choose asInfoMsg |> Info.stream model.Info |> Stream.map InfoMsg
          Stream.none |> Stream.choose asMagicMsg |> Magic.stream model.Magic |> Stream.map MagicMsg
        ]
```

To use tap you just pipe into into it e.g `msgs |> Stream.tap "1"`

**Comment by dbrattli** [comment]
The latest release btw have a `subStream` function that makes it easy to compose sub-streams and will split out the sub messages, feed them to the sub component and merge back the returned sub-stream. Thus the main stream and components are symmetric.

```fs
let subStream (stream: 'subModel -> Stream<'subMsg, 'name> -> Stream<'subMsg, 'name>) (subModel: 'subModel) (toSubMsg: 'msg -> 'subMsg option) (toMsg: 'subMsg -> 'msg) (name : 'name) (msgs: Stream<'msg, 'name>) =
        let subMsgs = Stream [ msgs |> AsyncRx.choose toSubMsg, name]
        let subMsgs' = stream subModel subMsgs |> map toMsg
        let msgs' = msgs |> chooseNot toSubMsg

        batch [
            subMsgs'
            msgs'
        ]
```

**Comment by dbrattli** [comment]
Fable.Reaction now uses it's own message loop and has no dependencies on Elmish. This makes it much easier to extend existing Elmish apps since Fable.Reaction components can be added as a one-liner into Elmish views.
