### ISSUE TITLE
Updating to Fable.Core 3.0 and friends

### ISSUE THREAD

**Issue by theimowski** [dbrattli/Fable.Reaction#19]
Hi, any plans on updating to latest versions of Fable.Core etc? I'd like to make the update for SAFE template, currently Fable.Reaction seems to be the only dependency we have that doesn't come with Fable.Core >3 support.
I'm happy to help with that if necessary

**Comment by dbrattli** [comment]
[Fable.Elmish.Reaction.3.0.0](https://www.nuget.org/packages/Fable.Elmish.Reaction/) was released 2 days ago, but I haven't had much time testing it. There might be a few changes of the API between the initial release for SAFE and v3 but I can check that out later today and help you out with getting things updated.

**Comment by theimowski** [comment]
Thanks @dbrattli I'll get back to you if I find any issues when upgrading

**Comment by theimowski** [comment]
I was looking at [Fable.Reaction](https://www.nuget.org/packages/Fable.Reaction) package - is it now replaced by Fable.Elmish.Reaction?

**Comment by theimowski** [comment]
Working now on updating SAFE template
I think I followed the instructions from your docs, but can't get it working:
https://github.com/theimowski/safe-template-issue-250-reaction here's what I got - it compiles but when I run it `fake build -t run` the InitialCountLoaded doesn't fire for some reason.

Also I get following warnings:
```
WARNING in ./.fable/Reaction.AsyncRx.2.1.0/Create.fs
Module Warning (from ./node_modules/fable-loader/index.js):
/Users/theimowski/sandbox/safe-template/250/.fable/Reaction.AsyncRx.2.1.0/Create.fs(166,17): (166,54) warning FABLE: Async.Start will behave as StartImmediate
 @ ./.fable/Fable.Elmish.Reaction.3.0.0/AsyncRx.fs 3:0-76 8:9-22 69:9-15
 @ ./src/Client/Client.fs
 @ ./src/Client/Client.fsproj
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/Client/Client.fsproj

WARNING in ./.fable/Reaction.AsyncRx.2.1.0/Create.fs
Module Warning (from ./node_modules/fable-loader/index.js):
/Users/theimowski/sandbox/safe-template/250/.fable/Reaction.AsyncRx.2.1.0/Create.fs(28,17): (28,60) warning FABLE: Async.Start will behave as StartImmediate
 @ ./.fable/Fable.Elmish.Reaction.3.0.0/AsyncRx.fs 3:0-76 8:9-22 69:9-15
 @ ./src/Client/Client.fs
 @ ./src/Client/Client.fsproj
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/Client/Client.fsproj
```

**Comment by dbrattli** [comment]
Ok, I'll look into it ...

**Comment by dbrattli** [comment]
These packages should fix the problem and the warning

- https://www.nuget.org/packages/Reaction.AsyncRx/2.1.2
- https://www.nuget.org/packages/Fable.Elmish.Reaction/3.0.1

**Comment by dbrattli** [comment]
But please hold off for a few days as I've decided to rename the project for Fable v3 so we wil get new namespaces and packages. The way to use the library will also change, so I can make a PR to your project when things are ready.

**Comment by dbrattli** [comment]
Done: https://github.com/theimowski/safe-template-issue-250-reaction/pull/1

PS: There might be other places in the SAFE template that you also want to update for the renaming to Elmish.Streams.
