### ISSUE TITLE
Not compatible with netcoreapp3.1/netstandard2.1 target

### ISSUE THREAD

**Issue by fradav** [dbrattli/Fable.Reaction#43]
When I choose netcoreapp3.1 target, Fable compilation fails with:
```plain
The type 'System.IAsyncDisposable' does not match the type 'IAsyncDisposable
```

Reverting to netstandard2.0 works.

**Comment by dbrattli** [comment]
Yes, `IAsyncDisposable` is now included so we should use that one instead for netcore. https://docs.microsoft.com/en-us/dotnet/api/system.iasyncdisposable?view=netcore-3.1

**Comment by fradav** [comment]
Unfortunately, the new `DisposeAsync` returns a `ValueTask` not an `Async`. Just avoid the namespace conflict should be the most sensible?

**Comment by dbrattli** [comment]
Yes, that is probably the the most sensible. Have been working so much with Oryx and `Task` lately that I've forgot for a moment that AsyncRx is `Async` 😄.

**Comment by fradav** [comment]
I see you updated AsyncRx, but you didn't change the name of the interface, so it's still a potential clash and we have to carefully fully qualify everywhere we make an "open System" (and that is often...)
Perhaps it's asking a lot, but would you mind to change `IAsyncDisposable` for `IFSharpAsyncDisposable` for example ? I really think it's more future proof.

**Comment by dbrattli** [comment]
The other option I'm considering is to rewrite the library to `Task` and use `IAsyncDisposable` when available. I just need to figure out how to handle this in Fable, but it should map better to promise anyways.

**Comment by fradav** [comment]
Pardon my ignorance but what's the advantages of `Task` over `Async`, other than the former is ubiquitous in .net ecosystem?

**Comment by dbrattli** [comment]
https://github.com/giraffe-fsharp/Giraffe/issues/53

**Comment by fradav** [comment]
Ok, I didn't know about performance improvements. What do you think about this https://github.com/pimbrouwers/falco over giraffe ?

**Comment by dbrattli** [comment]
Haven't tried it. But looking at the data-types of Falco I can see that Giraffe has another trick up its sleeve and uses continuations to improve the speed further: https://medium.com/@gerardtoconnor/carry-on-continuation-over-binding-pipelines-for-functional-web-58bd7e6ea009

**Comment by dbrattli** [comment]
I use the same trick to speed up `Async` vs `Sync` handling for maps and filters i.e https://github.com/dbrattli/Fable.Reaction/blob/master/AsyncRx/src/Transform.fs#L10

Thus `map` and `mapAsync` uses the same implementation, without `map` having to get any penalty for being sync.

**Comment by fradav** [comment]
Did you see that : https://github.com/fsharp/fslang-suggestions/issues/866 ?

**Comment by dbrattli** [comment]
Added suggested fix: https://github.com/dbrattli/Fable.Reaction/blob/master/AsyncRx/src/Builder.fs#L39

Name of interface renamed to `IAsyncRxDisposable`.

**Comment by dbrattli** [comment]
Closing as this issue should be fixed. Please re-open if you find any problems.

**Comment by fradav** [comment]
Everything works fine, many thanks!
Thanks also for this neat and cleanly designed Fable library. I must admit it is the main reason I'm sticking with Fable/F# for frontend projects.
I think it is a very nice implementation of the [meiosis pattern](http://meiosis.js.org/)
