### ISSUE TITLE
Support disposing AsyncDisposable multiple times

### ISSUE THREAD

**Issue by johannesegger** [dbrattli/Fable.Reaction#48]
`AsyncDisposable.DisposeAsync` should be idempotent, so disposing something multiple times should be the same as disposing it just once. `AsyncDisposable.DisposeAsync` can't tell if `cancel` itself is idempotent, so it should only call it once. I think this could be done with the following implementation:

```fsharp
type AsyncDisposable (cancel) =
    let mutable isDisposed = 0
    interface IAsyncRxDisposable with
        member this.DisposeAsync () =
#if FABLE_COMPILER
            if isDisposed = 0 then
                isDisposed <- 1
                cancel ()
#else
            if System.Threading.Interlocked.CompareExchange(&isDisposed, 1, 0) = 0 then
                cancel ()
#endif
            else
                Async.empty
```

I was about to create a PR with this change (and also used `AsyncDisposable.Create` everywhere instead of anonymous objects that implement `IAsyncRxDisposable`) but it wasn't easy to separate Core.fs and AsyncDisposable.fs because they depended on each other. And again if it's possible that library users can't create anonymous objects that *don't* follow this rule I would very much prefer that.
What do you say in general? Do you think it's worth to implement?

**Comment by dbrattli** [comment]
Thanks for reporting. We should fix this. I've made a commit to master that should make this easier and that uses `AsyncDisposable.Create()` instead of implementing the interface. We can recommend using it but we cannot force it, the same way as you cannot force it for anyone that implements `IDisposable`.
