### ISSUE TITLE
Fable.Reaction on other elmish platforms

### ISSUE THREAD

**Issue by OnurGumus** [dbrattli/Fable.Reaction#55]
Is it possible to make this thing work with nonweb elmish applications ? If I want to use this approach on Fabolous or other elmish platforms, how can I get started?

**Comment by dbrattli** [comment]
Some insight here: https://github.com/dbrattli/Fable.Reaction/issues/15#issuecomment-631872803

**Comment by OnurGumus** [comment]
Yeah, I understand, at least we need some way to figure out running the streams without Fable. It's good that you consider it. So I will close the ticket.

**Comment by OnurGumus** [comment]
For the sake of context if one looks for an elmish bound, more fable-neutral streams 
https://github.com/johannesegger/Fable.Elmish.Nile might be the right address at the moment.
