### ISSUE TITLE
Why Async.Start' ?

### ISSUE THREAD

**Issue by OnurGumus** [dbrattli/Fable.Reaction#76]
I am seeing this code:

```
static member Start' (computation:Async<unit>, ?cancellationToken: CancellationToken) : unit =
            #if FABLE_COMPILER
                Async.StartImmediate (computation, ?cancellationToken=cancellationToken)
            #else
                Async.Start (computation, ?cancellationToken=cancellationToken)
            #endif

```
But in fable Start and StartImmediate are the same thing.

**Comment by dbrattli** [comment]
Yes, but `AsyncRx` can be used outside of Fable. Sometimes we want to use `Start` and not `StartImmediate` for .NET environments. That could would then trigger a warning with Fable. This is to get rid of that warning.

**Comment by dbrattli** [comment]
FYI: https://github.com/fable-compiler/Fable/issues/1826

**Comment by OnurGumus** [comment]
btw there is a plugin for webpack which allows you to suppress warnings by text matching.
